server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/clientes/**
        - id: tienda-ropa
          uri: lb://tienda-ropa
          predicates:
            - Path=/categorias/**
