server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-cliente
              uri: lb://ms-cliente
              predicates:
                - Path=/clientes/**
              filters:
                - StripPrefix=1
            - id: tienda-ropa
              uri: lb://tienda-ropa
              predicates:
                - Path=/categorias/**


              # Si tu servicio real no expone /categoria/...:
#               filters:
#                 - StripPrefix=1
#server:
#  port: 9090
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
#  instance:
#    hostname: localhost
#
#
#spring:
#  cloud:
#
#
#    gateway:
#      discovery:
#        locator:
#          enable: true
#      routes:
#        - id: ms-cliente
#          uri: lb://MS-CLIENTE
#          predicates:
#            - Path=/api/clientes/**
#        - id: tienda-ropa
#          uri: lb://TIENDA-ROPA
#          predicates:
#            - Path=/categorias/**
