spring:
  application:
    name: tienda-ropa

  datasource:
    url: jdbc:mysql://localhost:3306/tienda_ropa
    username: root
    password: topgym123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7071

# Swagger OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
